apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-tier-app
  labels:
    app: two-tier-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: two-tier-app
  template:
    metadata:
      labels:
        app: two-tier-app
    spec:
      containers:
        - name: two-tier-app
          image: trainwithshubham/flaskapp:latest
          env:
            - name: MYSQL_HOST
              value: "10.244.0.47"          # this is your mysql's service clusture IP, Make sure to change it with yours
            - name: MYSQL_PASSWORD
              value: "admin"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_DB
              value: "mydb"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          resources:
            requests: 
             cpu: "500m"  
             memory: "64mi"
            limits: 
              cpu: "1000m"
              memory: "128mi"
          startupProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10      # Time before starting the probe
            periodSeconds: 5            # How often the probe runs
            failureThreshold: 2         # Number of failures before the pod is marked as unhealthy
          livenessProbe:    
            httpGet:
              path: /health
              port: 5000
           initialDelaySeconds: 2      # Time before starting the probe
           periodSeconds: 3            # How often the probe runs
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 2      # Time before starting the probe
            periodSeconds: 3            # How often the probe runs        
                

